cluster: mp2
 plot_features_RW:
  type: job-array
  time: 00:30:00 (HH:MM:SS)
  mem_per_cpu: 256 (MB or G)
  runs: 100
 RandomWalk:
   type: job-array
   time: 00:35:00 (HH:MM:SS)
   mem_per_cpu: 128 (M or G)
   episodes: 50000
 RW19GammaLambdaAlpha:
   type: job-array
   time: 00:30:00 (HH:MM:SS)
   mem_per_cpu: 512M (M or G)
   episodes: 1000
  plot_RW19DiscountRateLambdaSSGamma:
   type: job-array
   time: 00:10:00 (HH:MM:SS)
   mem_per_cpu: 128M (M or G)
   episodes: 1000
 MountainCar:
   type: job-array
   time: 08:00:00 (HH:MM:SS)
   mem_per_cpu: 512 (M or G)
   episodes: 100000
 PuddleWorld:
   type: job-array
   time: 08:00:00 (HH:MM:SS)
   mem_per_cpu: 512 (M or G)
   episodes: 100000
